### ISSUE TITLE
Not able to download via rclone 

### ISSUE THREAD

**Issue by gymnae** [backblaze-b2-samples/cloudflare-b2#1]
I created an issue on the rclone forum.
I'm unsure if the issue lies with rclone or this worker template
I think there's a problem with the request URL that is being built, the URI part /file/ appears to break the URL:
https://forum.rclone.org/t/backblaze-b2-integration-builds-wrong-url-for-cloudflare-cdn/

**Comment by AspieWaiter** [comment]
I have been playing with this and got it to work with this change. I am not a coder:

   const url = new URL(request.url);
   
   // Debug: Log initial url.pathname
   // Remove leading 'file/' from path if present
   let path = url.pathname.replace(/^\/?file\//, '/');
   
   // Debug: Log new path
   url.pathname = path;

   // Remove leading and trailing slashes for the local 'path' variable
    path = path.replace(/^\//, '').replace(/\/$/, '');

    // Split the path into segments
    const pathSegments = path.split('/');

**Comment by metadaddy** [comment]
This turned out to not be an issue: https://forum.rclone.org/t/backblaze-b2-integration-builds-wrong-url-for-cloudflare-cdn/42056/5
