### ISSUE TITLE
Improve experience of ALLOW_LIST_BUCKET=false

### ISSUE THREAD

**Issue by jonhoo** [backblaze-b2-samples/cloudflare-b2#11]
Currently, this immediately returns a 404 if trying to access the root of the bucket. Instead of returning a 404, how about turning the request into a request of `/index.html`? That way it's possible to still have a website at the root (this will still become a 404 if there's no `index.html`).

**Comment by jonhoo** [comment]
I ended up also making any URL that ends in `/` forward to `+ /index.html`, and have found that that works well for my cases at least. In case it's useful to anyone else, here's the diff:
```diff
diff --git a/index.js b/index.js
index b7d9378..69485b0 100644
--- a/index.js
+++ b/index.js
@@ -53,6 +53,10 @@ export default {
 
         // Remove leading slashes from path
         let path = url.pathname.replace(/^\//, '');
+        // Paths that end in a / get /index.html
+        if (path.endsWith('/')) {
+            path = path + 'index.html';
+        }
         // Remove trailing slashes
         path = path.replace(/\/$/, '');
         // Split the path into segments
@@ -62,13 +66,13 @@ export default {
             // Don't allow list bucket requests
             if ((env.BUCKET_NAME === "$path" && pathSegments.length < 2) // https://endpoint/bucket-name/
                 || (env.BUCKET_NAME !== "$path" && path.length === 0)) {   // https://bucket-name.endpoint/ or https://endpoint/
-                return new Response(null, {
-                    status: 404,
-                    statusText: "Not Found"
-                });
+                path = path + '/index.html';
             }
         }
 
+        // Write back the updated path
+        url.pathname = path;
+
         // Set upstream target hostname.
         switch (env.BUCKET_NAME) {
             case "$path":
```

**Comment by jonhoo** [comment]
Good call! Needs to be a "Transform Rule" though.

For reference for others, I created a rule with the expression:

```
(http.host eq "mydomain.com" and ends_with(http.request.uri.path, "/"))
```

and made it rewrite the path with a "dynamic" expression of

```
concat(http.request.uri.path, "index.html")
```

**Comment by jingyuanliang** [comment]
@metadaddy I agree that rewriting all paths ending in / to become /index.html ~breaks object storage semantics, but since the 404 for "root" is already something produced by the worker (so it attracts question like "why 404 instead of 403"), maybe we can allow users to customize this response, e.g. they can give 403, or they can also give 302 with a location (and they can customize whether it's index.html or index.htm). Only do this for the root (ListObjects) and not anything ending in /. What do you think?

**Comment by metadaddy** [comment]
@jingyuanliang Thanks for your perspective. I think perhaps the best way to do this might be to have another worker, that, ideally, shares common code with this one and has the root -> index functionality, as well as supporting a couple more features:

- Return error payload as HTML
- Configurable redirects

I could call it `cloudflare-b2-website`. What do you think?

> why 404 instead of 403

Yeah - it should really be 403, I think, to match the response from B2. I can't remember why I set it to 404!
