### ISSUE TITLE
All requests bypass CloudFlare caching

### ISSUE THREAD

**Issue by jonhoo** [backblaze-b2-samples/cloudflare-b2#13]
As far as I can tell, all my requests now end up with
```
cf-cache-status | BYPASS
```
(this is for a newly created bucket, so it shouldn't be hitting the old `max-age: 0` rule). I don't know whether this is because of the `Authorization` header that the worker adds or something else, but it effectively means I don't get any of the benefits of CloudFlare's CDN caching. I _suspect_ its `Authorization` since the worker [runs "in front" of caching](https://community.cloudflare.com/t/cache-in-front-of-worker/171258/13), and without a `Cache-Control: public` header in the response [CloudFlare won't cache the resource](https://developers.cloudflare.com/cache/concepts/cache-control/#conditions).

Is this expected?

**Comment by jonhoo** [comment]
Ah, yes, can confirm that it's also necessary to set
```json
{"cache-control":"public"}
```
in the "Bucket info" field for the bucket. Then caching starts working correctly. Probably worth adding to https://www.backblaze.com/docs/cloud-storage-deliver-private-backblaze-b2-content-through-cloudflare-cdn and to the README :)

**Comment by metadaddy** [comment]
Many thanks, @jonhoo - [I updated the README](https://github.com/backblaze-b2-samples/cloudflare-b2/blob/main/README.md#bucket-configuration), and my technical publications colleague [updated the article](https://www.backblaze.com/docs/cloud-storage-deliver-private-backblaze-b2-content-through-cloudflare-cdn#set-bucket-information).

**Comment by jonhoo** [comment]
Thank you!
