### ISSUE TITLE
Intermittent error around if-modified-since

### ISSUE THREAD

**Issue by johnmaguire** [backblaze-b2-samples/cloudflare-b2#15]
I get intermittent failures at times when attempting to load an image from a B2 bucket. When the failure occurs, I receive an XML message that mentions either the presence or absence (I am not sure!) of `if-modified-since` header. (I keep "automatically" refreshing the page when the error occurs, without thinking to capture it. I will try to add it here next time I see it.)

This issue has been ongoing since I first set this up in February 2023.

**Comment by patdx** [comment]
Using similar code and same issue, response code 400 and just caught the error, which looks like this:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<Error>\n    <Code>InvalidRequest</Code>\n    <Message>header 'if-modified-since' is listed in signed headers, but is not present</Message>\n</Error>
```

I'm not sure, Maybe the header is in the original request from the browser upstream, but Cloudflare strips the header from the outgoing request to Backblaze?

**Comment by johnmaguire** [comment]
@patdx Thanks for capturing the error. I've just realized it's easily reproducible which should make it easier to debug:

```
❯ curl https://example.com/fc9f0376-783a-474e-8866-14875c10182c.jpg -H 'if-modified-since: Tue, 7 Nov 2021 07:28:00 GMT'
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
    <Code>InvalidRequest</Code>
    <Message>header 'if-modified-since' is listed in signed headers, but is not present</Message>
</Error>
```

Although if you request the same URL twice, with the same date, it goes away.

Adding `if-modified-since` to the `UNSIGNABLE_HEADERS` array seems to resolve the issue: https://github.com/backblaze-b2-samples/cloudflare-b2/blob/main/index.js#L8

**Comment by patdx** [comment]
Thanks. I was hoping I could figure out *why* it gets modified by Cloudflare but after more research and observation for a few days I didn't make any progress on that. So I ended up making the same modification which seems to be working better.

**Comment by metadaddy** [comment]
I'm closing this, since it seems to be intermittent, and there is a workaround.
