### ISSUE TITLE
ERROR: Could not resolve "aws4fetch"

### ISSUE THREAD

**Issue by viasux** [backblaze-b2-samples/cloudflare-b2#17]
✘ [ERROR] Could not resolve "aws4fetch"

    index.js:6:26:
      6 │ import { AwsClient } from 'aws4fetch'
        ╵                           ~~~~~~~~~~~

  You can mark the path "aws4fetch" as external to exclude it from the bundle, which will remove this error.

✘ [ERROR] Build failed with 1 error:

  index.js:6:26: ERROR: Could not resolve "aws4fetch"

**Comment by viasux** [comment]
following https://www.backblaze.com/docs/cloud-storage-deliver-private-backblaze-b2-content-through-cloudflare-cdn

this happens when I run `npx wrangler deploy` or `npx wrangler publish`

**Comment by metadaddy** [comment]
Hi @viasux - you need to do `npm install` before deploying the worker. I'll add a section on deploying the worker to the README and include this.
