### ISSUE TITLE
there is no content-range in the b2 response when requested large with 'range: bytes=0-'

### ISSUE THREAD

**Issue by gillbates** [backblaze-b2-samples/cloudflare-b2#7]
Hi B2,

using 

```
curl -s -D - -o /dev/null GET https://f004.backblazeb2.com/file/gc-test-public/a_large_tar_file_5Gb.tar -H 'range: bytes=0-'
```

we got resp like:
```
HTTP/1.1 200
x-bz-file-name: a_large_tar_file_5Gb.tar
x-bz-file-id: 4_z4cd6dadda64893e173e30513_f2000d66df7d808ce_d20220627_m232055_c004_v0402004_t0005_u01656372055525
x-bz-content-sha1: none
X-Bz-Upload-Timestamp: 1656372055525
Accept-Ranges: bytes
Content-Type: application/x-tar
Content-Length: 4980920320
Date: Sun, 08 Oct 2023 01:57:54 GMT
```

so far the content-range header is missing, this will make we cannot drag the progress bar when playing a mp4 file in the browser.
In the latest chrome, it will send a request with 'range: bytes=0-' at first.
Other cdn would normally return something like:

```
HTTP/2 206
date: Sun, 08 Oct 2023 02:21:58 GMT
content-type: video/mp4
content-length: 901350987
content-range: bytes 0-901350986/901350987
```
where 901350987 is the full length of the object.

Can we fix this somehow?

**Comment by metadaddy** [comment]
Hi @gillbates - this is due to an issue where, if the client requests the range `0-`, B2 will return the whole file with a `200` status (instead of `206`) and no `Content-Range` header. I'll look at detecting this in the worker code, changing the status and adding `Content-Range` in the response to the client.

**Comment by gillbates** [comment]
> Hi @gillbates - this is due to an issue where, if the client requests the range `0-`, B2 will return the whole file with a `200` status (instead of `206`) and no `Content-Range` header. I'll look at detecting this in the worker code, changing the status and adding `Content-Range` in the response to the client.

thx @metadaddy 
Actually when you play one mp4 file in the browser. You could see this behavouir

![CleanShot 2023-10-09 at 04 53 40@2x](https://github.com/backblaze-b2-samples/cloudflare-b2/assets/783547/3a09c0e4-007b-4c88-898e-4961dfaaa929)

**Comment by metadaddy** [comment]
@gillbates Closing this, since it's not an issue with the Cloudflare Worker. 'Open-ended' range requests to the S3-compatible API result in a 206 response, with or without the worker:

Direct to B2's S3-compatible API:

```
% curl -i https://s3.us-west-004.backblazeb2.com/metadaddy-public/hello.txt -H "range: bytes=0-"
HTTP/1.1 206 
Accept-Ranges: bytes
Last-Modified: Fri, 20 Jan 2023 05:43:19 GMT
ETag: "f967e41d528bfef4f2cfa2df00f46d6c"
x-amz-meta-src_last_modified_millis: 1674193392403
Content-Range: bytes 0-18/19
x-amz-request-id: 87e30b0ed5ede2f9
x-amz-id-2: aMdk1BWYZOdgzsjXiY7ZmkTQVZJRjlmKX
x-amz-version-id: 4_zf1f51fb913357c4f74ed0c1b_f116377b1a4b77702_d20230120_m054319_c004_v0402013_t0050_u01674193399725
Content-Type: text/plain
Content-Length: 19
Date: Mon, 23 Oct 2023 19:51:51 GMT

Hello from US West
```

Via worker:

```
% curl -i https://cloudflare-b2.backblaze-se.workers.dev/hello.txt -H "range: bytes=0-"         
HTTP/2 206 
date: Mon, 23 Oct 2023 19:53:02 GMT
content-type: text/plain
content-length: 19
content-range: bytes 0-18/19
cf-ray: 81ac861b8e9b96e3-SJC
cf-cache-status: DYNAMIC
accept-ranges: bytes
etag: "f967e41d528bfef4f2cfa2df00f46d6c"
last-modified: Fri, 20 Jan 2023 05:43:19 GMT
x-amz-id-2: aMWQ1u2agOTEzJjU8Y85mNjSHZM5j8mJJ
x-amz-meta-src_last_modified_millis: 1674193392403
x-amz-request-id: 10a970a8ce99ce5a
x-amz-version-id: 4_zf1f51fb913357c4f74ed0c1b_f116377b1a4b77702_d20230120_m054319_c004_v0402013_t0050_u01674193399725
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=memm97kDVHiOYq24Jg8zdcpdj7HIvQ0CAHBSvwH4VSUuKnr9VC%2BiH1frXwT7z9m2WKIn%2B6XPkUGAa3jtNgjg1LfzIcIdvchiKiXIbcPIZEzo93nOtPxgvPU7GiCf8JlqM5vGFelZZCsdiAZ%2BUTQE78KvpeLH8rGRCg%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
alt-svc: h3=":443"; ma=86400

Hello from US West
```

It's only the B2 Native API that exhibits this behavior:

```
% curl -i https://f004.backblazeb2.com/file/metadaddy-public/hello.txt -H "range: bytes=0-"
HTTP/1.1 200 
x-bz-file-name: hello.txt
x-bz-file-id: 4_zf1f51fb913357c4f74ed0c1b_f116377b1a4b77702_d20230120_m054319_c004_v0402013_t0050_u01674193399725
x-bz-content-sha1: 2a98f2afb8e4b989133706a3d0f0308e9e4d6a7c
X-Bz-Upload-Timestamp: 1674193399725
Accept-Ranges: bytes
x-bz-info-src_last_modified_millis: 1674193392403
Content-Type: text/plain
Content-Length: 19
Date: Mon, 23 Oct 2023 19:54:15 GMT

Hello from US West
```

Word from Backblaze engineering is that, since clients may be relying on the current behavior, and it's not precluded by the HTTP spec, we can't change it without a revision to the API. In the meantime, if you use the S3-compatible API URL, B2 will respond with 206.

**Comment by gillbates** [comment]
@metadaddy thx for the info, ok, we would just switch to s3 compatible api endpoint, thx!
